/* Generador de datos: Inserciones en la BDD */

/* Productos (12) */
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('1', 'Caja pequeña 25mm', '0', '0,5');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('00', 'Caja pequeña 40mm', '0', '1');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja pequeña 60mm', '0', '2,3');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja pequeña 1cm', '0', '5');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja mediana 25mm', '0', '0,75');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja mediana 40mm', '0', '1,2');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja mediana 60mm', '0', '2,4');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja mediana 1cm', '0', '4,75');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja grande 25mm', '0', '1,3');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('00', 'Caja grande 40mm', '0', '2');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja grande 60mm', '0', '3');
INSERT INTO "SYSTEM"."PRODUCTO" (OID_P, NOMBRE, STOCK, PRECIOUNITARIO) VALUES ('0', 'Caja grande 1cm', '0', '4,5');

/* Masters */

INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1000', 'Cartón', '25x25x40', '25');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1001', 'Cartón', '25x25x40', '40');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1002', 'Cartón', '25x25x40', '60');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1003', 'Cartón', '25x25x40', '100');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1004', 'Cartón', '40x45x60', '25');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1005', 'Cartón', '40x45x60', '40');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1006', 'Cartón', '40x45x60', '60');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1007', 'Cartón', '40x45x60', '100');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1008', 'Cartón', '80x90x110', '25');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1009', 'Cartón', '80x90x110', '40');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1010', 'Cartón', '80x90x110', '60');
INSERT INTO "SYSTEM"."MASTERMAT" (OID_P, MATERIAL, MEDIDAS, CANAL) VALUES ('1011', 'Cartón', '80x90x110', '100');


